name: Office Football
version: 1.1.4
author: Max Quattromani
markdown: redcarpet
highlighter: rouge
baseurl:
email: pquattromani@citywidehomeloans.com
google_analytics: true
google_analytics_id: UA-50387096-9
jquery_version: 1.12.4

exclude: ['node_modules', 'scss']
