name: Office Football
version: 1.1.1
author: Max Quattromani
markdown: redcarpet
highlighter: rouge
baseurl:
email: max@maxquattromani.com
google_analytics: false
google_analytics_id: UA-XXXXXXXX-1
jquery_version: 1.9.0

exclude: ['node_modules', 'scss']
