name: Office Football
version: 1.1.2
author: Max Quattromani
markdown: redcarpet
highlighter: rouge
baseurl:
email: max@maxquattromani.com
google_analytics: true
google_analytics_id: UA-50387096-9
jquery_version: 1.9.0

exclude: ['node_modules', 'scss']
